// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drtcphgiwjojienkbkid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRydGNwaGdpd2pvamllbmtia2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODIwNjcsImV4cCI6MjA2NTg1ODA2N30._N0cpwBAV9nG2O779hq3Qc9hrcZU6ZyPbXZGyvWXTYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);